name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test

  create-push-image:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=version_tag;]${{ secrets.DOCKERHUB_USERNAME }}/chuck-norris-jokes:${GITHUB_REF}#$"refs/tags/v"}"
          echo "##[set-output name=latest_tag;]${{ secrets.DOCKERHUB_USERNAME }}/chuck-norris-jokes:latest"
